### ISSUE TITLE
Download GeoLite2-Country-CSV.zip is unavailable from December 31, 2019. Is there any solution or replacement?

### ISSUE THREAD

**Issue by owent** [v2ray/geoip#10]
Download GeoLite2-Country-CSV.zip is unavailable from December 31, 2019. Is there any solution or replacement?

See https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ for detail and I could not create a account. I don't know the reason.

**Comment by kslr** [comment]
let me try

**Comment by kslr** [comment]
fix
