### ISSUE TITLE
go get github.com/v2fly/geoip 报错

### ISSUE THREAD

**Issue by owent** [v2ray/geoip#25]
```bash
~> go get -insecure -v github.com/v2fly/geoip
github.com/v2fly/geoip (download)
v2ray.com/core/app/stats/command
# v2ray.com/core/app/stats/command
src/v2ray.com/core/app/stats/command/command.go:61:24: impossible type assertion:
        *"v2ray.com/core/app/stats".Manager does not implement "v2ray.com/core/features/stats".Manager (missing UnregisterCounter method)
```

**Comment by Loyalsoldier** [comment]
Fixed.

Use the following command to get the latest code:

```
go get -u -insecure -v github.com/v2fly/geoip
```

**Comment by owent** [comment]
Thanks.

**Comment by kingwilliam** [comment]
go get -u -insecure -v github.com/v2fly/geoip

出现以下error, 请问可以如何处理?谢谢

v2ray.com/core/transport/internet/quic
/root/go/src/v2ray.com/core/transport/internet/quic/dialer.go:153:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
/root/go/src/v2ray.com/core/transport/internet/quic/hub.go:109:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config

**Comment by kingwilliam** [comment]
https://github.com/2dust/v2rayNG/issues/837

已解决
